FROM python3.7

# set the working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txtt

# install requirements
RUN pip install -r requirements.txt

# add app
COPY . /usr/src/app

# run the servers
CMD python manage.py run -h 0.0.0.0
